permalink   : /:categories/:year/:title/
markdown    : kramdown
redcarpet:  
  input : GFM

gems: [jekyll-paginate, jekyll-gist]

paginate: 4 #6
comments: true
paginate_path: "/page/:num"

# source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed

# How do you change the background here?
cover: /images/journey.jpg

# TODO : need to fill this up.
# site title, description, meta_description, meta_keywords
name:
title: Arjun Biddanda
description: "Home"
keywords: "Arjun Biddanda, population genetics, math, blog"
url: http://aabiddanda.github.io
baseurl: ""
domain_name: aabiddanda.github.io
disqus_shortname: "arjunbiddanda"

author:
  name      : Arjun Biddanda
  email     : abiddanda@uchicago.edu
  url       : aabiddanda.github.io
  twitter   : http://twitter.com/aabiddanda
  github    : http://github.com/aabiddanda

