permalink   : /:categories/:year/:title/
markdown    : redcarpet
redcarpet:  
  input : GFM

gems: [jekyll-paginate]

paginate: 4 #6
comments: true
paginate_path: "/page/:num"

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed

# How do you change the background here?
cover: /assets/images/default-cover.png

# TODO : need to fill this up.
# site title, description, meta_description, meta_keywords
name:
title: Arjun Biddanda
description: "Home"
keywords: "Arjun Biddanda, population, genetics, blog"
url: http://arjunbiddanda.github.io
baseurl: ""
domain_name: arjunbiddanda.github.io
disqus_shortname: "arjunbiddanda"

author:
  name      : Arjun Biddanda
  email     : abiddanda[at]uchicago.edu
  url       : arjunbiddanda.github.io
  twitter   : http://twitter.com/arjunbiddanda
  github    : http://github.com/arjunbiddanda

