title:  Arjun Biddanda
tagline:  

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

google-ID: ''

menu:
- {name: 'Research', path: 'menu', url: 'research.html'}
- {name: 'Publications', path: 'menu', url: 'publications.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}
- {name: 'Blog', path: 'menu', url: 'blog.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/lenpaul'}
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}
